name: Check
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v4

     - name: Start Kafka
       uses: 280780363/kafka-action@v1.0
       with:
         kafka version: "latest"
         zookeeper version: "latest"
         kafka port: 9092
         zookeeper port: 2181
         auto create topic: "true"
         wait: "true"
         wait-timeout: "120"
     - name: Wait for Kafka to be ready
       run: |
           echo "Waiting for Kafka..."
           for i in {1..10}; do
             if nc -z localhost 9092; then
               echo "Kafka is up!"
               exit 0
             fi
             sleep 3
           done
           echo "Kafka failed to start"
           exit 1

     - name: Setup jdk
       uses: actions/setup-java@v4
       with:
            distribution: 'temurin'
            java-version: '21'
     - name: Verify
       run: java -version
     - name: Unit tests
       run:  mvn -B test --file pom.xml



