name: Check
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v4
     - name: Install deps
       run: |
        sudo apt update
        sudo apt install -y openjdk-17-jdk
        echo "JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64" >> $GITHUB_ENV
     - name: Verify
       run: java -version

